name: ollama
services:
  open-webui:
    ports:
      - "3333:8080"
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    volumes:
      - "${HOME}/personal/ollama/ollama-webui:/app/backend/data"
    container_name: open-webui
    restart: unless-stopped
    image: ghcr.io/open-webui/open-webui:main
    depends_on:
      - ollama

  ollama:
    restart: unless-stopped
    volumes:
      - "${HOME}/personal/ollama/ollama:/root/.ollama"
    ports:
      - "11434:11434"
    container_name: ollama
    image: ollama/ollama:latest
