name: ollama
services:
  open-webui:
    ports:
      - "3333:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "/home/thalo/ollama-webui:/app/backend/data"
    container_name: open-webui
    restart: unless-stopped
    image: ghcr.io/open-webui/open-webui:main
    depends_on:
      - ollama

  ollama:
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    volumes:
      - "~/ollama:/root/.ollama"
    ports:
      - "11434:11434"
    container_name: ollama
    image: ollama/ollama
